config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Defines the root path route ("/")
  root 'home#index'

  namespace :api do
    resources :basket, only: :create
    get 'basket/basket_material_count', to: 'basket#basket_material_count'
  end

  resources :favourites, only: %i[index create destroy]

  resources :material, only: :show

  resources :basket, only: :index
  resources :basket_materials do
    collection do
      get :update_total_price
    end
  end
  delete 'basket.:id', to: 'basket#destroy'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/basket_material.rb
# frozen_string_literal: true

class BasketMaterial < ApplicationRecord
  validates :length, presence: true, numericality: { greater_than: 0 }

  belongs_to :material
end

app/models/favourite.rb
# frozen_string_literal: true

class Favourite < ApplicationRecord
  belongs_to :material
end

app/models/material.rb
# frozen_string_literal: true

class Material < ApplicationRecord
  validates :name, presence: true
  validates :description, presence: true
  validates :thickness, presence: true, numericality: { greater_than: 0 }
  validates :width, presence: true, numericality: { greater_than: 0 }
  validates :price, presence: true, numericality: { greater_than: 0 }

  monetize :price_cents, allow_nil: true

  has_one_attached :image, dependent: :destroy
  has_one :favourite, dependent: :destroy
  has_many :basket_material, dependent: :destroy
end

app/controllers/api/basket_controller.rb
# frozen_string_literal: true

module Api
  class BasketController < ApplicationController
    protect_from_forgery with: :null_session

    def create
      basket_material = BasketMaterial.create!(basket_material_params)

      respond_to do |format|
        format.json do
          render json: basket_material.to_json, status: :created
        end
      end
    end

    def basket_material_count
      count = BasketMaterial.all.count

      respond_to do |format|
        format.json do
          render json: count.to_json, status: :found
        end
      end
    end

    private

    def basket_material_params
      params.permit(:material_id, :length)
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/basket_controller.rb
# frozen_string_literal: true

class BasketController < ApplicationController
  def index
    @basket_materials = BasketMaterial.all.includes(:material).order('materials.name')
  end

  def destroy
    basket_material = BasketMaterial.find(params[:id])
    basket_material.destroy

    respond_to do |format|
      format.html do
        flash[:success] = "#{basket_material.material.name} removed from basket"
        redirect_to basket_index_path
      end
    end
  end
end

app/controllers/basket_materials_controller.rb
# frozen_string_literal: true

class BasketMaterialsController < ApplicationController
  def create
    BasketMaterial.create!(basket_material_params)

    render turbo_stream: turbo_stream.replace('trolley_counter', partial: 'layouts/trolley_counter',
                                                                 locals: { count: BasketMaterial.count })
  end

  def update_total_price
    length = params[:length].to_i
    price = params[:price].to_i
    render turbo_stream: turbo_stream.replace('total_price_info', partial: 'material/total_info',
                                                                  locals: { length:, price: })
  end

  private

  def basket_material_params
    params.required(:basket_material).permit(:material_id, :length)
  end
end

app/controllers/favourites_controller.rb
# frozen_string_literal: true

class FavouritesController < ApplicationController
  def index
    @favourites = Favourite.all.includes(:material).order('materials.name')
  end

  def create
    favourite = Favourite.create!(favourite_params)

    render turbo_stream: turbo_stream.replace("favourite_star_#{favourite.material_id}", partial: 'layouts/favourite_star',
                                                                                         locals: { favourited: true, favourite:, material: favourite.material })
  end

  def destroy
    favourite = Favourite.find(params[:id])
    favourite.destroy

    render turbo_stream: turbo_stream.replace("favourite_star_#{favourite.material_id}", partial: 'layouts/favourite_star',
                                                                                         locals: { favourited: false, favourite:, material: favourite.material })
  end

  private

  def favourite_params
    params.permit(:material_id)
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index
    @materials = Material.all.order(:name)
  end
end

app/controllers/material_controller.rb
# frozen_string_literal: true

class MaterialController < ApplicationController
  def show
    @material = Material.find(params[:id])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/basket_helper.rb
# frozen_string_literal: true

module BasketHelper
  def calculate_material_cost(price, length)
    price * length
  end

  def calculate_basket_total(basket_materials)
    total = 0
    basket_materials.each do |basket_material|
      total += basket_material.material.price * basket_material.length
    end
    total
  end

  def basket_populated?
    count = BasketMaterial.count
    count >= 1
  end

  def number_of_items_in_basket
    BasketMaterial.count
  end
end

app/helpers/favourite_helper.rb
# frozen_string_literal: true

module FavouriteHelper
  def favourited?(params)
    favourite = Favourite.find_by(material_id: params[:id])
    favourite.nil? ? false : true
  end

  def get_favourite_id(params)
    favourite = Favourite.find_by(material_id: params[:id])
    favourite.nil? ? '' : favourite.id
  end

  def get_favourite(params)
    Favourite.find_by(material_id: params[:id])
  end
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
  def favourited?(params)
    favourite = Favourite.find_by(material_id: params[:id])
    favourite.nil? ? false : true
  end

  def get_favourite_id(params)
    favourite = Favourite.find_by(material_id: params[:id])
    favourite.nil? ? '' : favourite.id
  end
end

app/views/basket/index.html.erb
<div class="sticky-header-padding"> 
    <%= render 'layouts/messages' %>
    <div 
        data-controller="basket"
        class="container mx-auto p-8"
    >
        <h2 class="pb-2">Basket</h2>
        <div class="flex justify-center text-left"> 
            <div class="overflow-x-auto sm:-mx-6 lg:-mx-8">
                <div class="inline-block min-w-full sm:px-6 lg:px-8">
                    <div class="overflow-hidden">
                        <table>
                            <tbody>
                                <% @basket_materials.each do |basket_material| %>
                                    <tr class="border-b hover:bg-gray-100 whitespace-nowrap">
                                        <td><%= image_tag basket_material.material.image, class: "h-12 w-12 rounded-sm" %></td>
                                        <td class="p-4 text-teal-500 hover:text-teal-300 focus:underline"><%= link_to basket_material.material.name, material_path(basket_material.material) %></td>
                                        <td class="p-4 font-normal text-center"><%= basket_material.length %>m</td>
                                        <td class="p-4 font-normal text-center"><%= humanized_money_with_symbol(calculate_material_cost(basket_material.material.price, basket_material.length)) %></td>
                                        <td class="px-2 py-4 text-teal-500 hover:text-teal-300 focus:underline delete-button">    
                                            <%= button_to basket_index_path(basket_material), method: :delete do %>
                                                <%= inline_svg_tag('delete_icon.svg', class: 'h-5 w-5') %>
                                            <% end %>
                                        </td>
                                    </tr>
                                <% end %>
                            </tbody>
                        </table>
                    </div>
                    <div class="mt-2">
                        <% if @basket_materials.count > 0 %>
                            <div class="divide-y divide-gray-200"></div>
                            <dl class="space-y-4">
                                <div class="flex items-center justify-between pt-6">
                                    <dt class="text-base">Total</dt>
                                    <dd class="text-base font-medium text-gray-900"><%= humanized_money_with_symbol(calculate_basket_total(@basket_materials)) %></dd>
                                </div>
                            </dl>
                            <div class="pt-6">
                                <button 
                                    data-action="click->basket#proceedToCheckout"
                                    class="w-full bg-teal-500 hover:bg-teal-300 border border-transparent rounded-md shadow-sm py-3 px-4 text-base font-medium text-white focus:ring-offset-gray-50 focus:ring-teal-500"
                                >
                                    Complete purchase
                                </button>
                            </div>
                        <% else %>
                            <p>There are no items in your basket</p>
                        <% end %>
                    </div>
                </div>
            </div> 
        </div>
    </div>
</div>

app/views/favourites/index.html.erb
<div class="sticky-header-padding">
    <%= render 'layouts/messages' %>
    <div class="container mx-auto p-8">
        <h2 class="pb-2">Materials/Favourites</h2>
        <div class="flex justify-center text-left"> 
            <div class="overflow-x-auto sm:-mx-6 lg:-mx-8">
                <div class="inline-block min-w-full sm:px-6 lg:px-8">
                    <div class="overflow-hidden">
                        <table>
                            <tbody>
                                <% @favourites.each do |favourite| %>
                                    <tr class="border-b hover:bg-gray-100 whitespace-nowrap">
                                        <td><%= image_tag favourite.material.image, class: "h-12 w-12 rounded-sm" %></td>
                                        <td class="p-4 text-teal-500 hover:text-teal-300 focus:underline"><%= link_to favourite.material.name, material_path(favourite.material) %></td>
                                        <td class="px-2 py-4 text-teal-500 hover:text-teal-300 focus:underline delete-button">    
                                            <%= button_to favourites_path(favourite), method: :delete do %>
                                                <%= inline_svg_tag('delete_icon.svg', class: 'h-5 w-5') %>
                                            <% end %>
                                        </td>
                                    </tr>
                                <% end %>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>





    

app/views/home/index.html.erb
<div class="sticky-header-padding">
    <div class="container mx-auto p-8">
        <h2 class="pb-2">Materials/Door trim</h2>
        <ul role="list" class="grid grid-cols-1 gap-x-4 gap-y-8 sm:grid-cols-3 sm:gap-x-6 lg:grid-cols-4 xl:gap-x-8">
            <% @materials.each do |material| %>
                <li class="relative">
                    <div>
                        <%= link_to material_path(material) do %>
                            <div class="group block w-full aspect-w-10 aspect-h-7 rounded-lg bg-gray-100 focus-within:ring-2 focus-within:ring-offset-2 focus-within:ring-red-500 overflow-hidden hover:opacity-75 relative">
                                <%= image_tag material.image, class: "object-cover pointer-events-none group-hover:opacity-75" %>
                                <button type="button" class="absolute inset-0 focus:outline-none">
                                    <span class="sr-only">View details</span>
                                </button>
                            </div>
                            <h4 class="mt-2 block font-medium text-gray-900 truncate pointer-events-none"><%= material.name %></h4>
                        <% end %>
                        <div class="flex flex-row-reverse p-2 w-full absolute star-icon">
                            <%= render "layouts/favourite_star", favourited: favourited?(material), favourite: get_favourite(material), material: material %>
                        </div>
                    </div>
                    <table class="text-sm pointer-default w-full">
                        <tbody>
                            <tr class="border-b hover:bg-gray-100 whitespace-nowrap">
                                <td class="text-gray-500">Thickness: </td>
                                <td class="text-right"><%= material.thickness %></td>
                            </tr>
                            <tr class="border-b hover:bg-gray-100 whitespace-nowrap">
                                <td class="text-gray-500">Width: </td>
                                <td class="text-right"><%= material.width %></td>
                            </tr>
                            <tr class="border-b hover:bg-gray-100">
                                <td class="text-gray-500">Water tightness: </td>
                                <td class="text-right whitespace-nowrap"><%= material.water_tightness %></td>
                            </tr>
                            <tr class="border-b hover:bg-gray-100">
                                <td class="text-gray-500">Burglar resistance: </td>
                                <td class="text-right whitespace-nowrap"><%= material.burglar_resistance %></td>
                            </tr>
                            <tr class="hover:bg-gray-100">
                                <td><%= material.application %></td>
                            </tr>
                        </tbody>
                    </table>
                </li>
            <% end %>
        </ul>
    </div>
</div>

app/views/layouts/_favourite_star.html.erb
<%= turbo_frame_tag "favourite_star_#{material.id}" do %>
    <% if favourited %>
        <%= button_to favourite_path(favourite), method: :delete, class: "text-teal-500" do %>
            <%= inline_svg_tag('star_icon.svg') %>
        <% end %>
    <% else %>
        <%= button_to favourites_path(material_id: material.id), method: :post, class: "text-transparent" do %>
            <%= inline_svg_tag('star_icon.svg') %>
        <% end %>
    <% end %>
<% end %>

app/views/layouts/_header.html.erb
<header
    data-controller="header"
    class="bg-slate-800 fixed w-full z-10"
>
    <div class="max-w-7xl mx-auto px-2 sm:px-4 lg:px-8">
        <div class="relative h-16 flex justify-between nav-container">
            <div class="relative z-10 px-2 flex lg:px-0">
                 <div class="flex-shrink-0 flex items-center">
                    <%= link_to root_path, class: "logo-link flex items-center focus:underline" do %>
                        <%= inline_svg_tag('schuco_logo.svg', class: 'h-6 w-30') %>
                    <% end %>
                </div>
            </div>
            <div class="absolute inset-y-0 right-0 flex items-center pr-2 sm:static sm:inset-auto sm:ml-6 sm:pr-0 invisible md:visible text-gray-400">
                <%= link_to basket_index_path, class: "p-1 rounded-full p-2 hover:text-teal-300 hover:bg-slate-700 focus:outline-none focus:ring-2 focus:ring-teal-300" do %>
                    <span class="sr-only">View basket</span>
                    <svg
                        id="trolley-icon"
                        xmlns="http://www.w3.org/2000/svg"
                        viewBox="0 0 576 512"
                        class="h-6 w-6"
                        fill="<%= basket_populated? ? '#14b8a6' : 'currentcolor' %>"
                        data-action="update-cart-icon@window->header#updateBasketIcon"
                        data-populated-colour="#14b8a6"
                    >
                        <path d="M0 24C0 10.7 10.7 0 24 0H69.5c22 0 41.5 12.8 50.6 32h411c26.3 0 45.5 25 38.6 50.4l-41 152.3c-8.5 31.4-37 53.3-69.5 53.3H170.7l5.4 28.5c2.2 11.3 12.1 19.5 23.6 19.5H488c13.3 0 24 10.7 24 24s-10.7 24-24 24H199.7c-34.6 0-64.3-24.6-70.7-58.5L77.4 54.5c-.7-3.8-4-6.5-7.9-6.5H24C10.7 48 0 37.3 0 24zM128 464a48 48 0 1 1 96 0 48 48 0 1 1 -96 0zm336-48a48 48 0 1 1 0 96 48 48 0 1 1 0-96z"/>
                    </svg>
                <% end %>
                <p class="pl-1">
                  <%= render "layouts/trolley_counter", count: number_of_items_in_basket %>
                </p>
                <div class="ml-3 relative">
                    <div data-header-target="openMenu" class="relative z-10 flex items-center">
                        <button type="button" class="rounded-md p-2 inline-flex items-center justify-center hover:bg-slate-700 hover:text-white focus:outline-none focus:ring-2 focus:ring-teal-300">
                        <span class="sr-only">Open menu</span>
                        <%= inline_svg_tag('burger_icon.svg', class: 'block h-8 w-8') %>
                    </div>
                    <div
                        class="hidden origin-top-right absolute right-0 mt-2 w-48 rounded-md shadow-lg py-1 bg-white ring-1 ring-black ring-opacity-5 focus:outline-none divide-y divide-slate-200 z-20"
                        id="menu-dropdown-items"
                        role="menu"
                        aria-orientation="vertical"
                        aria-labelledby="menu-button"
                        tabindex="-1"
                        data-transition-enter="transition ease-out duration-100"
                        data-transition-enter-start="transform opacity-0 scale-95"
                        data-transition-enter-end="transform opacity-100 scale-100"
                        data-transition-leave="transition ease-in duration-75"
                        data-transition-leave-start="transform opacity-100 scale-100"
                        data-transition-leave-end="transform opacity-0 scale-95"
                    >
                        <div class="py-1 text-sm text-gray-700" role="none">
                            <%= link_to "Favourites", favourites_path, class: "block px-4 py-2 hover:bg-gray-100", id: "menu-item-0" %>
                            <%= link_to "Basket", basket_index_path, class: "block px-4 py-2 hover:bg-gray-100", id: "menu-item-1" %>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>

app/views/layouts/_messages.html.erb
<% if flash[:success].present? %>
    <div class="bg-teal-100 border-t-4 border-teal-500 text-teal-900 px-4 py-3 shadow-md" role="alert">
        <div class="flex">
            <div>
                <p class="font-bold"><%= flash[:success] %></p>
            </div>
        </div>
    </div>
<% end %>

app/views/layouts/_trolley_counter.html.erb
<%= turbo_frame_tag "trolley_counter" do %>
  <% if count > 0 %>
    <%= count %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Schueco door trim products</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <%= favicon_link_tag asset_path("door_icon.svg") %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <%= yield %>
  </body>
</html>

app/views/material/_material_description_modal.html.erb
<div 
    data-controller="modal" 
    id="modal-wrapper"
    class="hidden relative z-10" 
    aria-labelledby="modal-title" 
    role="dialog" 
    aria-modal="true"
>
    <div 
        id="modal-backdrop" 
        class="hidden fixed inset-0 bg-gray-500 bg-opacity-75 transition-opacity"
        data-transition-enter="ease-out duration-300"
        data-transition-enter-start="opacity-0"
        data-transition-enter-end="opacity-100"
        data-transition-leave="ease-in duration-200"
        data-transition-leave-start="opacity-100"
        data-transition-leave-end="opacity-0"
    >
    </div>
    <div class="fixed z-10 inset-0 overflow-y-auto">
        <div class="flex items-end sm:items-center justify-center min-h-full p-4 text-center sm:p-0">
            <div 
                id="modal-panel" 
                class="hidden relative bg-white rounded-lg px-4 pt-5 pb-4 text-left overflow-hidden shadow-xl transform transition-all sm:my-8 sm:max-w-xl sm:w-full sm:p-6"
                data-transition-enter="ease-out duration-300"
                data-transition-enter-start="opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
                data-transition-enter-end="opacity-100 translate-y-0 sm:scale-100"
                data-transition-leave="ease-in duration-200"
                data-transition-leave-start="opacity-100 translate-y-0 sm:scale-100"
                data-transition-leave-end="opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
                data-action="show-description-modal@window->modal#showModal"
            >
                <div class="flex mb-5">
                    <div class="flex-none cursor-pointer text-gray-500" data-modal-target="closeButton">
                        <%= inline_svg_tag('close_icon.svg', class: 'h-5 w-5') %>
                    </div>
                </div>
                <div>
                    <%= @material.description %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/material/_material_info.html.erb
<div
    data-controller="material"
    data-price-per-metre="<%= @material.price %>"
    data-material-id="<%= @material.id %>"
    class="max-w-2xl mx-auto pt-10 pb-16 px-4 sm:px-6 lg:max-w-7xl lg:pt-8 lg:pb-12 lg:px-8 lg:grid lg:grid-cols-3 lg:grid-rows-[auto,auto,1fr] lg:gap-x-8"
    >
    <div class="lg:col-span-2 lg:border-r lg:border-gray-200 lg:pr-8">
      <p class="mb-2">Product information</p>
      <table class="pointer-default w-full">
        <tbody>
          <tr class="border-b hover:bg-gray-100 whitespace-nowrap">
            <td class="text-gray-500">Thickness: </td>
            <td class="text-right"><%= @material.thickness %></td>
          </tr>
          <tr class="border-b hover:bg-gray-100 whitespace-nowrap">
            <td class="text-gray-500">Width: </td>
            <td class="text-right"><%= @material.width %></td>
          </tr>
          <tr class="border-b hover:bg-gray-100">
            <td class="text-gray-500">Water tightness: </td>
            <td class="text-right whitespace-nowrap"><%= @material.water_tightness %></td>
          </tr>
          <tr class="border-b hover:bg-gray-100">
            <td class="text-gray-500">Burglar resistance: </td>
            <td class="text-right whitespace-nowrap"><%= @material.burglar_resistance %></td>
          </tr>
          <tr class="hover:bg-gray-100">
            <td class="text-gray-500">Applications: </td>
            <td class="text-right"><%= @material.application %></td>
          </tr>
          <tr class="hover:bg-gray-100">
            <td class="pt-2"><%= humanized_money_with_symbol(@material.price) %> per metre</td>
          </tr>
        </tbody>
      </table>
    </div>
    <div class="mt-4 lg:mt-0 lg:row-span-3">
      <div class="mt-10 lg:mt-0">
        <%= turbo_frame_tag "add_to_basket_form" do %>
          <%= form_for BasketMaterial.new do |f| %>
            <%= f.hidden_field :material_id, value: @material.id %>
            <h2 class="text-xl font-medium text-gray-900"><%= humanized_money_with_symbol(@material.price) %> per metre</h2>
            <div class="isolate -space-y-px rounded-md shadow-sm mt-6">
              <div class="relative border border-gray-300 rounded-md px-3 py-2 focus-within:z-10 focus-within:ring-1 focus-within:ring-teal-500 focus-within:border-teal-500">
                <label for="name" class="block text-xs font-medium text-gray-900">Metres</label>
                <%= f.number_field :length, required: true, placeholder: 0, class: "block w-full border-0 p-0 text-gray-900 focus:ring-0 sm:text-sm placeholder-gray-500", data: { action: "material#updateTotalPrice", material_target: "lengthInput" } %>
              </div>
            </div>
            <div class="mt-6">
              <div class="divide-y divide-gray-200"></div>
              <dl class="space-y-4">
                <%= render "total_info", length: 0, price: @material.price %>
              </dl>
              <div class="pt-6">
                <%= f.submit "Add to basket", class: "w-full bg-teal-500 hover:bg-teal-300 border border-transparent rounded-md shadow-sm py-3 px-4 text-base font-medium text-white focus:ring-offset-gray-50 focus:ring-teal-500" %>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="py-10 lg:py-6 lg:col-start-1 lg:col-span-2 lg:border-r lg:border-gray-200 lg:pr-8">
      <div>
        <h3 class="sr-only">Description</h3>
        <div>
          <p class="text-base text-gray-900"><%= truncate @material.description, length: 500 %></p>
          <% if @material.description.length > 500 %>
            <p
                data-action="click->material#showDescription"
                class="text-lg font-medium underline cursor-pointer text-teal-500 hover:text-teal-300"
                >
                Show more >
            </p>
          <% end %>
        </div>
      </div>
    </div>
</div>

app/views/material/_total_info.html.erb
<%= turbo_frame_tag "total_price_info" do %>
  <% total_price = price * length %>
  <div class="flex items-center justify-between">
    <dt class="text-sm"><%= humanized_money_with_symbol(price) %> x <%= length %>m</dt>
    <dd class="text-sm font-medium text-gray-900"><%= humanized_money_with_symbol(total_price) %></dd>
  </div>
  <div class="flex items-center justify-between border-t border-gray-200 pt-6">
    <dt class="text-base">Total</dt>
    <dd class="text-base font-medium text-gray-900">
      <%= humanized_money_with_symbol(total_price) %>
    </dd>
  </div>
<% end %>

app/views/material/show.html.erb
<div class="sticky-header-padding">
    <div class="bg-white">
        <div class="pt-6">
            <div class="max-w-2xl mx-auto px-4 flex items-center space-x-2 sm:px-6 lg:max-w-7xl lg:px-8 mb-2">
                <h1 class="font-semibold text-4xl"><%= @material.name %></h1>
            </div>
            <div class="max-w-2xl mx-auto px-4 flex justify-end items-center space-x-2 sm:px-6 lg:max-w-7xl lg:px-8 cursor-pointer">
                <div class="star-icon">
                    <%= render "layouts/favourite_star", favourited: favourited?(@material), favourite: get_favourite(@material), material: @material %>
                </div>
                <span>Favourite</span>
            </div>
            <div class="mt-6 max-w-2xl mx-auto sm:px-6 lg:max-w-7xl lg:px-8">
                <div class="aspect-auto overflow-hidden block">
                    <%= image_tag @material.image, class: "w-full h-full object-center object-cover" %>
                </div>
            </div>
            <%= render "material_info" %>
            <div class="max-w-2xl mx-auto sm:px-6 lg:max-w-7xl lg:px-8">
                <hr>
            </div>
        </div>
    </div>
</div>


<%= render "material_description_modal" %>